import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://myqpieokhkvgqjujppkv.supabase.co',
  process.env.SUPABASE_SERVICE_KEY ?? ''
)

const products = [
  // ── Laitiers → inputs ─────────────────────────────────────────
  { code: 'IN-LC1', dept_id: 'inputs', name_fr: 'Lait Concentré Entier', name_en: 'Whole Condensed Milk', ref_fr: '410g / boîte · 1 kg / boîte · Vrac 25 kg', ref_en: '410g / tin · 1 kg / tin · Bulk 25 kg', photo_alt_fr: 'lait concentré entier · boîte gala', photo_alt_en: 'whole condensed milk · gala tin', image: '/assets/product-lait-gala.png', brand: 'FAGOU Select', formats: ['410g / boîte', '1 kg / boîte', 'Vrac 25 kg'], availability: 'available', badge: 'export', description_fr: 'Lait concentré entier sucré de haute qualité, idéal pour la pâtisserie, les boissons et la cuisine africaine et européenne.', description_en: 'High-quality sweetened condensed whole milk, ideal for pastry, beverages, and African and European cuisine.', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 1 },
  { code: 'IN-LC2', dept_id: 'inputs', name_fr: 'Lait Concentré Écrémé', name_en: 'Skimmed Condensed Milk', ref_fr: '410g / boîte · 1 kg / boîte', ref_en: '410g / tin · 1 kg / tin', photo_alt_fr: 'lait concentré écrémé · nora', photo_alt_en: 'skimmed condensed milk · nora', image: '/assets/product-creamer-nora.png', brand: 'FAGOU Select', formats: ['410g / boîte', '1 kg / boîte'], availability: 'on-request', badge: 'export', description_fr: "Lait concentré écrémé non sucré, adapté à l'industrie agroalimentaire, boulangerie industrielle et productions laitières.", description_en: 'Unsweetened skimmed condensed milk, suitable for the food industry, industrial bakery, and dairy productions.', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20'", sort_order: 2 },

  // ── Sauces → inputs ───────────────────────────────────────────
  { code: 'IN-MY1', dept_id: 'inputs', name_fr: 'Mayonnaise Classique', name_en: 'Classic Mayonnaise', ref_fr: '5 L / seau · 10 L / seau · 200 L / fût', ref_en: '5 L / bucket · 10 L / bucket · 200 L / drum', photo_alt_fr: 'mayonnaise classique · gala', photo_alt_en: 'classic mayonnaise · gala', image: '/assets/product-mayo-gala.png', brand: 'FAGOU Gourmet', formats: ['5 L / seau', '10 L / seau', '200 L / fût'], availability: 'available', badge: 'premium', description_fr: 'Mayonnaise classique haute densité, conditionnée en grand format pour la restauration et la distribution.', description_en: 'High-density classic mayonnaise, packaged in large format for catering and distribution.', packaging_tonnes: '15 t / conteneur', packaging_palettes: '18 palettes', packaging_conteneurs: "FCL 20'", sort_order: 3 },
  { code: 'IN-KT', dept_id: 'inputs', name_fr: 'Ketchup Tomate', name_en: 'Tomato Ketchup', ref_fr: '1 kg / bouteille · 5 L / seau · 10 L / bidon', ref_en: '1 kg / bottle · 5 L / bucket · 10 L / can', photo_alt_fr: 'ketchup tomate · gourmet', photo_alt_en: 'tomato ketchup · gourmet', image: '/assets/product-mayo-nita.png', brand: 'FAGOU Gourmet', formats: ['1 kg / bouteille', '5 L / seau', '10 L / bidon'], availability: 'available', badge: 'export', description_fr: "Ketchup tomate de haute qualité, élaboré à partir de concentré de tomates, idéal pour la restauration et l'export.", description_en: 'High-quality tomato ketchup made from tomato concentrate, ideal for catering and export.', packaging_tonnes: '15 t / conteneur', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20'", sort_order: 4 },
  { code: 'IN-SP', dept_id: 'inputs', name_fr: 'Sauce Pimentée', name_en: 'Hot Sauce', ref_fr: '500 ml / bouteille · 5 L / seau', ref_en: '500 ml / bottle · 5 L / bucket', photo_alt_fr: 'sauce pimentée africaine', photo_alt_en: 'african hot sauce', image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80', brand: 'FAGOU Afrique', formats: ['500 ml / bouteille', '5 L / seau'], availability: 'on-request', badge: 'new', description_fr: "Sauce pimentée africaine authentique, recette traditionnelle adaptée à l'export, en grands conditionnements pour professionnels.", description_en: 'Authentic African hot sauce, traditional recipe adapted for export, in large packaging for professionals.', packaging_tonnes: '10 t / conteneur', packaging_palettes: '16 palettes', packaging_conteneurs: "FCL 20'", sort_order: 5 },

  // ── Légumes → agrifood ────────────────────────────────────────
  { code: 'AG-OR', dept_id: 'agrifood', name_fr: 'Oignons Rouges', name_en: 'Red Onions', ref_fr: 'calibre 60–80 mm, sac filet 25 kg', ref_en: 'size 60–80 mm, 25 kg net bag', photo_alt_fr: 'oignons rouges · sac gala 25 kg', photo_alt_en: 'red onions · gala 25 kg bag', image: '/assets/product-oignons-rouges-gala.png', formats: ['10 kg / sac', '25 kg / sac', '50 kg / sac'], availability: 'available', badge: 'export', description_fr: "Oignons rouges calibrés, sélectionnés pour leur qualité et leur conservation longue durée. Idéaux pour l'export vers l'Afrique.", description_en: 'Calibrated red onions, selected for their quality and long shelf life. Ideal for export to Africa.', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '25 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 1 },
  { code: 'AG-OJ', dept_id: 'agrifood', name_fr: 'Oignons Jaunes', name_en: 'Yellow Onions', ref_fr: 'calibre standard, sac 10–25 kg ou vrac', ref_en: 'standard size, 10–25 kg bag or bulk', photo_alt_fr: 'oignons jaunes · qualité export', photo_alt_en: 'yellow onions · export quality', image: 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=800&q=80', formats: ['10 kg / sac', '25 kg / sac', 'Vrac'], availability: 'available', badge: 'export', description_fr: 'Oignons jaunes de qualité supérieure, cultivés selon les standards européens. Disponibles en vrac ou en sacs.', description_en: 'Superior quality yellow onions, grown according to European standards. Available in bulk or bags.', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '25 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 2 },
  { code: 'AG-PDT', dept_id: 'agrifood', name_fr: 'Pommes de Terre', name_en: 'Potatoes', ref_fr: 'calibre export, sac 25–50 kg ou vrac', ref_en: 'export caliber, 25–50 kg bag or bulk', photo_alt_fr: 'pommes de terre · calibre export', photo_alt_en: 'potatoes · export caliber', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&q=80', formats: ['25 kg / sac', '50 kg / sac', 'Vrac'], availability: 'available', badge: 'export', description_fr: 'Pommes de terre fraîches européennes, calibre export, adaptées à toutes utilisations culinaires et à la transformation industrielle.', description_en: 'Fresh European potatoes, export caliber, suitable for all culinary uses and industrial processing.', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 3 },
  { code: 'AG-GA', dept_id: 'agrifood', name_fr: 'Ail Blanc', name_en: 'White Garlic', ref_fr: 'calibre 5,5–6 cm, sac filet 10 kg', ref_en: 'size 5.5–6 cm, 10 kg net bag', photo_alt_fr: 'ail · sacs gala 10 kg', photo_alt_en: 'garlic · gala 10 kg bags', image: '/assets/product-ail-gala.png', formats: ['5 kg / sac', '10 kg / sac', '20 kg / sac'], availability: 'available', badge: 'premium', description_fr: "Ail blanc séché, calibré et trié, d'origine européenne. Fort pouvoir aromatique, idéal pour l'industrie agroalimentaire.", description_en: 'Dried, calibrated and sorted white garlic of European origin. Strong aromatic power, ideal for the food industry.', packaging_tonnes: '15 t / conteneur', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20'", sort_order: 4 },

  // ── Poissons → agrifood ───────────────────────────────────────
  { code: 'AG-FF1', dept_id: 'agrifood', name_fr: 'Maquereau Congelé', name_en: 'Frozen Mackerel', ref_fr: 'entier ou filets, carton 10–20 kg', ref_en: 'whole or fillets, 10–20 kg case', photo_alt_fr: 'maquereau congelé · carton', photo_alt_en: 'frozen mackerel · case', image: '/assets/product-poissons.png', formats: ['Carton 10 kg', 'Carton 20 kg', 'Vrac congelé'], availability: 'available', badge: 'export', description_fr: "Maquereaux congelés entiers ou en filets, pêche atlantique certifiée, très consommés en Afrique de l'Ouest et centrale.", description_en: 'Whole or filleted frozen mackerel, certified Atlantic fishing, widely consumed in West and Central Africa.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 5 },
  { code: 'AG-FS1', dept_id: 'agrifood', name_fr: 'Sardines en Conserve', name_en: 'Canned Sardines', ref_fr: '125g / boîte · 425g / boîte · Carton 48', ref_en: '125g / tin · 425g / tin · Case of 48', photo_alt_fr: 'sardines en conserve · export', photo_alt_en: 'canned sardines · export', image: '/assets/product-morue.png', brand: 'FAGOU Select', formats: ['125g / boîte', '425g / boîte', 'Carton 48 boîtes'], availability: 'available', badge: 'export', description_fr: "Sardines en conserve à l'huile ou à la sauce tomate, qualité export, conditionnement idéal pour les marchés africains.", description_en: 'Sardines canned in oil or tomato sauce, export quality, ideal packaging for African markets.', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 6 },

  // ── Bœuf → frozen ─────────────────────────────────────────────
  { code: 'FZ-BF1', dept_id: 'frozen', name_fr: 'Quartiers de Bœuf Congelés', name_en: 'Frozen Beef Quarters', ref_fr: 'avant ~60–80 kg · arrière ~100–120 kg', ref_en: 'forequarter ~60–80 kg · hindquarter ~100–120 kg', photo_alt_fr: 'quartiers bœuf congelés · origine UE', photo_alt_en: 'frozen beef quarters · EU origin', image: 'https://images.unsplash.com/photo-1588347818036-c6e8a7e4c7b4?w=800&q=80', formats: ['Quartier avant ~60-80 kg', 'Quartier arrière ~100-120 kg'], availability: 'available', badge: 'export', description_fr: "Quartiers de bœuf congelés d'origine européenne certifiée, idéaux pour la boucherie africaine et la restauration.", description_en: 'Frozen beef quarters of certified European origin, ideal for African butcheries and catering.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 1 },
  { code: 'FZ-BF2', dept_id: 'frozen', name_fr: 'Découpes de Bœuf Congelées', name_en: 'Frozen Beef Cuts', ref_fr: 'épaule, cuisse, jarret · carton 10–20 kg', ref_en: 'shoulder, thigh, shank · 10–20 kg case', photo_alt_fr: 'découpes bœuf congelées · sous vide', photo_alt_en: 'frozen beef cuts · vacuum packed', image: 'https://images.unsplash.com/photo-1588347818036-c6e8a7e4c7b4?w=800&q=80', formats: ['Carton 10 kg', 'Carton 15 kg', 'Carton 20 kg'], availability: 'on-request', badge: 'premium', description_fr: 'Découpes spécifiques de bœuf (épaule, cuisse, jarret) congelées selon les normes CE, emballage sous vide.', description_en: 'Specific beef cuts (shoulder, thigh, shank) frozen according to EC standards, vacuum packed.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 2 },

  // ── Porc → frozen ─────────────────────────────────────────────
  { code: 'FZ-PK1', dept_id: 'frozen', name_fr: 'Pieds de Porc Congelés', name_en: 'Frozen Pork Feet', ref_fr: 'carton 10 kg · carton 20 kg · vrac congelé', ref_en: '10 kg case · 20 kg case · frozen bulk', photo_alt_fr: 'pieds de porc congelés · qualité UE', photo_alt_en: 'frozen pork feet · EU quality', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80', formats: ['Carton 10 kg', 'Carton 20 kg', 'Vrac congelé'], availability: 'available', badge: 'export', description_fr: 'Pieds de porc congelés de qualité européenne, très demandés sur les marchés africains pour la gastronomie locale.', description_en: 'Frozen pork feet of European quality, highly sought after on African markets for local gastronomy.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 3 },
  { code: 'FZ-PK2', dept_id: 'frozen', name_fr: 'Oreilles de Porc Congelées', name_en: 'Frozen Pork Ears', ref_fr: 'carton 10 kg · carton 20 kg', ref_en: '10 kg case · 20 kg case', photo_alt_fr: 'oreilles de porc congelées · origine UE', photo_alt_en: 'frozen pork ears · EU origin', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80', formats: ['Carton 10 kg', 'Carton 20 kg'], availability: 'available', badge: 'export', description_fr: "Oreilles de porc congelées, produit très apprécié en Afrique centrale et occidentale, origine UE certifiée.", description_en: 'Frozen pork ears, highly appreciated product in Central and West Africa, certified EU origin.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 4 },

  // ── Volaille → frozen ─────────────────────────────────────────
  { code: 'FZ-PL1', dept_id: 'frozen', name_fr: 'Poulet Entier Congelé', name_en: 'Frozen Whole Chicken', ref_fr: 'calibre 900g–1,2 kg · carton 10–15 kg', ref_en: '900g–1.2kg calibrated · 10–15 kg case', photo_alt_fr: 'poulet entier congelé · certifié CE', photo_alt_en: 'frozen whole chicken · EC certified', image: '/assets/product-volaille.png', formats: ['Carton 10 kg (~8 pièces)', 'Carton 15 kg (~12 pièces)'], availability: 'available', badge: 'export', description_fr: "Poulets entiers congelés d'origine européenne, calibrés 900g–1,2 kg, certifiés CE, idéaux pour les marchés africains.", description_en: 'Whole frozen chickens of European origin, 900g–1.2kg calibrated, EC certified, ideal for African markets.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 5 },
  { code: 'FZ-PL2', dept_id: 'frozen', name_fr: 'Cuisses de Poulet Congelées', name_en: 'Frozen Chicken Legs', ref_fr: 'carton 10 kg · 15 kg · 20 kg', ref_en: '10 kg · 15 kg · 20 kg case', photo_alt_fr: 'cuisses poulet congelées · export', photo_alt_en: 'frozen chicken legs · export', image: '/assets/product-volaille.png', formats: ['Carton 10 kg', 'Carton 15 kg', 'Carton 20 kg'], availability: 'available', badge: 'export', description_fr: 'Cuisses de poulet congelées, produit très demandé sur le marché africain, conditionnement adapté à la distribution locale.', description_en: 'Frozen chicken legs, highly demanded product on the African market, packaging adapted to local distribution.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 6 },
  { code: 'FZ-PL3', dept_id: 'frozen', name_fr: 'Ailes de Poulet Congelées', name_en: 'Frozen Chicken Wings', ref_fr: 'carton 10 kg · carton 20 kg', ref_en: '10 kg case · 20 kg case', photo_alt_fr: 'ailes poulet congelées · qualité sup.', photo_alt_en: 'frozen chicken wings · superior quality', image: '/assets/product-volaille.png', formats: ['Carton 10 kg', 'Carton 20 kg'], availability: 'on-request', badge: 'new', description_fr: 'Ailes de poulet congelées de qualité supérieure, idéales pour la restauration rapide et les marchés africains.', description_en: 'Superior quality frozen chicken wings, ideal for fast food catering and African markets.', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré", sort_order: 7 },

  // ── Œufs → inputs ─────────────────────────────────────────────
  { code: 'IN-EG1', dept_id: 'inputs', name_fr: 'Œufs Frais Calibrés', name_en: 'Fresh Calibrated Eggs', ref_fr: 'calibre M/L · plateau 30 · carton 360', ref_en: 'M/L grade · tray 30 · carton 360', photo_alt_fr: 'œufs frais calibrés · élevage UE', photo_alt_en: 'fresh calibrated eggs · EU farming', image: '/assets/product-eggs-gala.png', formats: ['Plateau 30 œufs', 'Carton 360 œufs', 'Palette 14 400 œufs'], availability: 'available', badge: 'export', description_fr: "Œufs frais calibre M/L d'élevage européen certifié, conditionnés en plateaux et en palettes pour l'export.", description_en: 'Fresh M/L grade eggs from certified European farming, packaged in trays and pallets for export.', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40'", sort_order: 6 },
  { code: 'IN-EG2', dept_id: 'inputs', name_fr: "Poudre d'Œuf Entier", name_en: 'Whole Egg Powder', ref_fr: 'sac 25 kg · carton 10 kg', ref_en: '25 kg bag · 10 kg carton', photo_alt_fr: "poudre d'œuf entier · industrie", photo_alt_en: 'whole egg powder · industry', image: '/assets/product-eggs-gala.png', brand: 'FAGOU Pro', formats: ['Sac 25 kg', 'Carton 10 kg'], availability: 'on-request', badge: 'premium', description_fr: "Poudre d'œuf entier déshydratée, haute solubilité, idéale pour l'industrie boulangère, pâtissière et agroalimentaire.", description_en: 'Dehydrated whole egg powder, high solubility, ideal for bakery, pastry, and food processing industries.', packaging_tonnes: '15 t / conteneur', packaging_palettes: '18 palettes', packaging_conteneurs: "FCL 20'", sort_order: 7 },

  // ── Huiles → pko ──────────────────────────────────────────────
  { code: 'OL-PKR', dept_id: 'pko', name_fr: 'Huile de Palme Raffinée', name_en: 'Refined Palm Oil', ref_fr: '1 L / 5 L / 20 L / fût 180 kg', ref_en: '1 L / 5 L / 20 L / 180 kg drum', photo_alt_fr: 'huile de palme raffinée · RSPO', photo_alt_en: 'refined palm oil · RSPO', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80', brand: 'FAGOU Agri', formats: ['1 L / bouteille', '5 L / bidon', '20 L / bidon', '180 kg / fût'], availability: 'available', badge: 'export', description_fr: "Huile de palme raffinée RBD, 100% pure, certifiée RSPO, très utilisée dans la cuisine africaine et l'industrie alimentaire.", description_en: 'Refined RBD palm oil, 100% pure, RSPO certified, widely used in African cuisine and the food industry.', oil_percentage: '100% huile de palme', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20' / FCL 40'", sort_order: 1 },
  { code: 'OL-PKO', dept_id: 'pko', name_fr: 'Huile de Palme Brute (CPO)', name_en: 'Crude Palm Oil (CPO)', ref_fr: 'vrac tanker · fût 200 L', ref_en: 'bulk tanker · 200 L drum', photo_alt_fr: 'huile de palme brute · CPO', photo_alt_en: 'crude palm oil · CPO', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80', brand: 'FAGOU Agri', formats: ['Vrac tanker', '200 L / fût'], availability: 'to-confirm', badge: 'export', description_fr: 'Huile de palme brute de première pression, destination industrie de raffinage, conditionnement en vrac ou en fûts.', description_en: 'Crude palm oil from first pressing, destination refining industry, packaged in bulk or drums.', oil_percentage: '98% acides gras libres < 5%', packaging_tonnes: '25 t / conteneur', packaging_conteneurs: "Tanker / FCL 20'", sort_order: 2 },
]

async function migrate() {
  console.log('Nettoyage de catalogue_products...')
  const { error: delErr } = await supabase.from('catalogue_products').delete().neq('code', '__none__')
  if (delErr) { console.error('❌ Suppression:', delErr.message); return }
  console.log('✅ Table vidée\n')

  console.log('Insertion des 22 produits...')
  const { error: insErr } = await supabase.from('catalogue_products').insert(products)
  if (insErr) { console.error('❌ Insertion:', insErr.message); return }
  console.log(`✅ ${products.length} produits insérés dans catalogue_products\n`)

  console.log('Migration terminée. Tu peux supprimer la table "products" dans Supabase.')
}

migrate()
