import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://myqpieokhkvgqjujppkv.supabase.co'
const SUPABASE_ANON_KEY = process.env.SUPABASE_SERVICE_KEY ?? ''

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

// ── DONNÉES PRODUITS ────────────────────────────────────────────
const products = [
  { id: 'lait-concentre-entier', category_id: 'dairy', name_fr: 'Lait Concentré Entier', name_en: 'Whole Condensed Milk', description_fr: 'Lait concentré entier sucré de haute qualité, idéal pour la pâtisserie, les boissons et la cuisine africaine et européenne.', description_en: 'High-quality sweetened condensed whole milk, ideal for pastry, beverages, and African and European cuisine.', image: '/assets/product-lait-gala.png', brand: 'FAGOU Select', formats: ['410g / boîte', '1 kg / boîte', 'Vrac 25 kg'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'lait-concentre-ecreme', category_id: 'dairy', name_fr: 'Lait Concentré Écrémé', name_en: 'Skimmed Condensed Milk', description_fr: "Lait concentré écrémé non sucré, adapté à l'industrie agroalimentaire, boulangerie industrielle et productions laitières.", description_en: 'Unsweetened skimmed condensed milk, suitable for the food industry, industrial bakery, and dairy productions.', image: '/assets/product-creamer-nora.png', brand: 'FAGOU Select', formats: ['410g / boîte', '1 kg / boîte'], availability: 'on-request', badge: 'export', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'mayonnaise-classique', category_id: 'sauces', name_fr: 'Mayonnaise Classique', name_en: 'Classic Mayonnaise', description_fr: 'Mayonnaise classique haute densité, conditionnée en grand format pour la restauration et la distribution.', description_en: 'High-density classic mayonnaise, packaged in large format for catering and distribution.', image: '/assets/product-mayo-gala.png', brand: 'FAGOU Gourmet', formats: ['5 L / seau', '10 L / seau', '200 L / fût'], availability: 'available', badge: 'premium', packaging_tonnes: '15 t / conteneur', packaging_palettes: '18 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'ketchup-tomate', category_id: 'sauces', name_fr: 'Ketchup Tomate', name_en: 'Tomato Ketchup', description_fr: "Ketchup tomate de haute qualité, élaboré à partir de concentré de tomates, idéal pour la restauration et l'export.", description_en: 'High-quality tomato ketchup made from tomato concentrate, ideal for catering and export.', image: '/assets/product-mayo-nita.png', brand: 'FAGOU Gourmet', formats: ['1 kg / bouteille', '5 L / seau', '10 L / bidon'], availability: 'available', badge: 'export', packaging_tonnes: '15 t / conteneur', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'sauce-pimentee', category_id: 'sauces', name_fr: 'Sauce Pimentée', name_en: 'Hot Sauce', description_fr: "Sauce pimentée africaine authentique, recette traditionnelle adaptée à l'export, en grands conditionnements pour professionnels.", description_en: 'Authentic African hot sauce, traditional recipe adapted for export, in large packaging for professionals.', image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80', brand: 'FAGOU Afrique', formats: ['500 ml / bouteille', '5 L / seau'], availability: 'on-request', badge: 'new', packaging_tonnes: '10 t / conteneur', packaging_palettes: '16 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'oignons-rouges', category_id: 'vegetables', name_fr: 'Oignons Rouges', name_en: 'Red Onions', description_fr: "Oignons rouges calibrés, sélectionnés pour leur qualité et leur conservation longue durée. Idéaux pour l'export vers l'Afrique.", description_en: 'Calibrated red onions, selected for their quality and long shelf life. Ideal for export to Africa.', image: '/assets/product-oignons-rouges-gala.png', formats: ['10 kg / sac', '25 kg / sac', '50 kg / sac'], availability: 'available', badge: 'export', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '25 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'oignons-jaunes', category_id: 'vegetables', name_fr: 'Oignons Jaunes', name_en: 'Yellow Onions', description_fr: 'Oignons jaunes de qualité supérieure, cultivés selon les standards européens. Disponibles en vrac ou en sacs.', description_en: 'Superior quality yellow onions, grown according to European standards. Available in bulk or bags.', image: 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=800&q=80', formats: ['10 kg / sac', '25 kg / sac', 'Vrac'], availability: 'available', badge: 'export', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '25 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'pommes-de-terre', category_id: 'vegetables', name_fr: 'Pommes de Terre', name_en: 'Potatoes', description_fr: 'Pommes de terre fraîches européennes, calibre export, adaptées à toutes utilisations culinaires et à la transformation industrielle.', description_en: 'Fresh European potatoes, export caliber, suitable for all culinary uses and industrial processing.', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&q=80', formats: ['25 kg / sac', '50 kg / sac', 'Vrac'], availability: 'available', badge: 'export', packaging_tonnes: "25 t / conteneur 20'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'ail-blanc', category_id: 'vegetables', name_fr: 'Ail Blanc', name_en: 'White Garlic', description_fr: "Ail blanc séché, calibré et trié, d'origine européenne. Fort pouvoir aromatique, idéal pour l'industrie agroalimentaire.", description_en: 'Dried, calibrated and sorted white garlic of European origin. Strong aromatic power, ideal for the food industry.', image: '/assets/product-ail-gala.png', formats: ['5 kg / sac', '10 kg / sac', '20 kg / sac'], availability: 'available', badge: 'premium', packaging_tonnes: '15 t / conteneur', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'boeuf-congelé-quartiers', category_id: 'beef', name_fr: 'Quartiers de Bœuf Congelés', name_en: 'Frozen Beef Quarters', description_fr: "Quartiers de bœuf congelés d'origine européenne certifiée, idéaux pour la boucherie africaine et la restauration.", description_en: 'Frozen beef quarters of certified European origin, ideal for African butcheries and catering.', image: 'https://images.unsplash.com/photo-1588347818036-c6e8a7e4c7b4?w=800&q=80', formats: ['Quartier avant ~60-80 kg', 'Quartier arrière ~100-120 kg'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'boeuf-congele-decoupes', category_id: 'beef', name_fr: 'Découpes de Bœuf Congelées', name_en: 'Frozen Beef Cuts', description_fr: 'Découpes spécifiques de bœuf (épaule, cuisse, jarret) congelées selon les normes CE, emballage sous vide.', description_en: 'Specific beef cuts (shoulder, thigh, shank) frozen according to EC standards, vacuum packed.', image: 'https://images.unsplash.com/photo-1588347818036-c6e8a7e4c7b4?w=800&q=80', formats: ['Carton 10 kg', 'Carton 15 kg', 'Carton 20 kg'], availability: 'on-request', badge: 'premium', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'porc-congelé-pieds', category_id: 'pork', name_fr: 'Pieds de Porc Congelés', name_en: 'Frozen Pork Feet', description_fr: 'Pieds de porc congelés de qualité européenne, très demandés sur les marchés africains pour la gastronomie locale.', description_en: 'Frozen pork feet of European quality, highly sought after on African markets for local gastronomy.', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80', formats: ['Carton 10 kg', 'Carton 20 kg', 'Vrac congelé'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'porc-congelé-oreilles', category_id: 'pork', name_fr: 'Oreilles de Porc Congelées', name_en: 'Frozen Pork Ears', description_fr: "Oreilles de porc congelées, produit très apprécié en Afrique centrale et occidentale, origine UE certifiée.", description_en: 'Frozen pork ears, highly appreciated product in Central and West Africa, certified EU origin.', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80', formats: ['Carton 10 kg', 'Carton 20 kg'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'poulet-congelé-entier', category_id: 'poultry', name_fr: 'Poulet Entier Congelé', name_en: 'Frozen Whole Chicken', description_fr: "Poulets entiers congelés d'origine européenne, calibrés 900g–1,2 kg, certifiés CE, idéaux pour les marchés africains.", description_en: 'Whole frozen chickens of European origin, 900g–1.2kg calibrated, EC certified, ideal for African markets.', image: '/assets/product-volaille.png', formats: ['Carton 10 kg (~8 pièces)', 'Carton 15 kg (~12 pièces)'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'cuisses-poulet-congelées', category_id: 'poultry', name_fr: 'Cuisses de Poulet Congelées', name_en: 'Frozen Chicken Legs', description_fr: 'Cuisses de poulet congelées, produit très demandé sur le marché africain, conditionnement adapté à la distribution locale.', description_en: 'Frozen chicken legs, highly demanded product on the African market, packaging adapted to local distribution.', image: '/assets/product-volaille.png', formats: ['Carton 10 kg', 'Carton 15 kg', 'Carton 20 kg'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'ailes-poulet-congelées', category_id: 'poultry', name_fr: 'Ailes de Poulet Congelées', name_en: 'Frozen Chicken Wings', description_fr: 'Ailes de poulet congelées de qualité supérieure, idéales pour la restauration rapide et les marchés africains.', description_en: 'Superior quality frozen chicken wings, ideal for fast food catering and African markets.', image: '/assets/product-volaille.png', formats: ['Carton 10 kg', 'Carton 20 kg'], availability: 'on-request', badge: 'new', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'poisson-maquereau-congelé', category_id: 'seafood', name_fr: 'Maquereau Congelé', name_en: 'Frozen Mackerel', description_fr: "Maquereaux congelés entiers ou en filets, pêche atlantique certifiée, très consommés en Afrique de l'Ouest et centrale.", description_en: 'Whole or filleted frozen mackerel, certified Atlantic fishing, widely consumed in West and Central Africa.', image: '/assets/product-poissons.png', formats: ['Carton 10 kg', 'Carton 20 kg', 'Vrac congelé'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 40'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40' réfrigéré" },
  { id: 'poisson-sardine-conserve', category_id: 'seafood', name_fr: 'Sardines en Conserve', name_en: 'Canned Sardines', description_fr: "Sardines en conserve à l'huile ou à la sauce tomate, qualité export, conditionnement idéal pour les marchés africains.", description_en: 'Sardines canned in oil or tomato sauce, export quality, ideal packaging for African markets.', image: '/assets/product-morue.png', brand: 'FAGOU Select', formats: ['125g / boîte', '425g / boîte', 'Carton 48 boîtes'], availability: 'available', badge: 'export', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '22 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'oeufs-frais-calibres', category_id: 'eggs', name_fr: 'Œufs Frais Calibrés', name_en: 'Fresh Calibrated Eggs', description_fr: "Œufs frais calibre M/L d'élevage européen certifié, conditionnés en plateaux et en palettes pour l'export.", description_en: 'Fresh M/L grade eggs from certified European farming, packaged in trays and pallets for export.', image: '/assets/product-eggs-gala.png', formats: ['Plateau 30 œufs', 'Carton 360 œufs', 'Palette 14 400 œufs'], availability: 'available', badge: 'export', packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 40'" },
  { id: 'poudre-oeuf-entier', category_id: 'eggs', name_fr: "Poudre d'Œuf Entier", name_en: 'Whole Egg Powder', description_fr: "Poudre d'œuf entier déshydratée, haute solubilité, idéale pour l'industrie boulangère, pâtissière et agroalimentaire.", description_en: 'Dehydrated whole egg powder, high solubility, ideal for bakery, pastry, and food processing industries.', image: '/assets/product-eggs-gala.png', brand: 'FAGOU Pro', formats: ['Sac 25 kg', 'Carton 10 kg'], availability: 'on-request', badge: 'premium', packaging_tonnes: '15 t / conteneur', packaging_palettes: '18 palettes', packaging_conteneurs: "FCL 20'" },
  { id: 'huile-palme-raffinee', category_id: 'oils', name_fr: 'Huile de Palme Raffinée', name_en: 'Refined Palm Oil', description_fr: "Huile de palme raffinée RBD, 100% pure, certifiée RSPO, très utilisée dans la cuisine africaine et l'industrie alimentaire.", description_en: 'Refined RBD palm oil, 100% pure, RSPO certified, widely used in African cuisine and the food industry.', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80', brand: 'FAGOU Agri', formats: ['1 L / bouteille', '5 L / bidon', '20 L / bidon', '180 kg / fût'], availability: 'available', badge: 'export', oil_percentage: '100% huile de palme', packaging_tonnes: "20 t / conteneur 20'", packaging_palettes: '20 palettes', packaging_conteneurs: "FCL 20' / FCL 40'" },
  { id: 'huile-palme-brute', category_id: 'oils', name_fr: 'Huile de Palme Brute (CPO)', name_en: 'Crude Palm Oil (CPO)', description_fr: 'Huile de palme brute de première pression, destination industrie de raffinage, conditionnement en vrac ou en fûts.', description_en: 'Crude palm oil from first pressing, destination refining industry, packaged in bulk or drums.', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80', brand: 'FAGOU Agri', formats: ['Vrac tanker', '200 L / fût'], availability: 'to-confirm', badge: 'export', oil_percentage: '98% acides gras libres < 5%', packaging_tonnes: '25 t / conteneur', packaging_conteneurs: 'Tanker / FCL 20\'' },
]

// ── DONNÉES NEWS ────────────────────────────────────────────────
const news = [
  { id: 'fagou-export-afrique-2024', title_fr: "FAGOU SRL renforce ses exportations vers l'Afrique de l'Ouest", title_en: 'FAGOU SRL strengthens its exports to West Africa', summary_fr: "FAGOU SRL annonce l'extension de ses routes d'exportation vers 5 nouveaux pays d'Afrique de l'Ouest avec des accords de distribution locaux.", summary_en: 'FAGOU SRL announces the extension of its export routes to 5 new West African countries with local distribution agreements.', content_fr: "FAGOU SRL, entreprise belge spécialisée dans l'import-export agroalimentaire depuis 2013, annonce l'extension significative de ses activités en Afrique de l'Ouest.", content_en: 'FAGOU SRL, a Belgian company specializing in agri-food import-export since 2013, announces a significant expansion of its activities in West Africa.', category: 'Actualités', published_at: '2024-11-15', image: 'https://images.unsplash.com/photo-1494522358652-f30e61a60313?w=800&q=80', author: 'FAGOU SRL' },
  { id: 'certification-qualite-2024', title_fr: 'FAGOU SRL obtient de nouvelles certifications qualité européennes', title_en: 'FAGOU SRL obtains new European quality certifications', summary_fr: "Nos produits répondent désormais aux standards les plus élevés de l'UE. FAGOU SRL élargit son portefeuille de certifications qualité.", summary_en: 'Our products now meet the highest EU standards. FAGOU SRL expands its quality certification portfolio.', content_fr: "FAGOU SRL est fière d'annoncer l'obtention de nouvelles certifications qualité européennes pour l'ensemble de sa gamme de produits agroalimentaires.", content_en: 'FAGOU SRL is proud to announce the obtaining of new European quality certifications for its entire range of agri-food products.', category: 'Certifications', published_at: '2024-09-20', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', author: 'FAGOU SRL' },
  { id: 'foire-alimentaire-bruxelles-2024', title_fr: 'FAGOU SRL présent à la Foire Alimentaire de Bruxelles', title_en: 'FAGOU SRL present at the Brussels Food Fair', summary_fr: 'Retrouvez FAGOU SRL au stand B24 lors de la prochaine édition de la Foire Alimentaire de Bruxelles pour découvrir nos nouveaux produits.', summary_en: 'Find FAGOU SRL at stand B24 at the next edition of the Brussels Food Fair to discover our new products.', content_fr: "FAGOU SRL participera à la prochaine édition de la Foire Alimentaire de Bruxelles, l'un des événements les plus importants du secteur agroalimentaire en Belgique.", content_en: 'FAGOU SRL will participate in the next edition of the Brussels Food Fair, one of the most important events in the agri-food sector in Belgium.', category: 'Événements', published_at: '2024-07-10', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80', author: 'FAGOU SRL' },
]

// ── DONNÉES PARTENAIRES ─────────────────────────────────────────
const partners = [
  { id: 'fagou-logistics', name_fr: 'FAGOU Logistics', name_en: 'FAGOU Logistics', description_fr: "Filiale logistique de FAGOU SRL, spécialisée dans le transport réfrigéré et la gestion de conteneurs entre l'Europe et l'Afrique.", description_en: 'Logistics subsidiary of FAGOU SRL, specializing in refrigerated transport and container management between Europe and Africa.', logo: 'https://images.unsplash.com/photo-1494522358652-f30e61a60313?w=200&q=80', country: 'Belgique' },
  { id: 'africom-distribution', name_fr: 'AfriCom Distribution', name_en: 'AfriCom Distribution', description_fr: "Partenaire de distribution en Afrique de l'Ouest et centrale, réseau de 200+ points de vente.", description_en: 'Distribution partner in West and Central Africa, network of 200+ points of sale.', logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&q=80', country: "Côte d'Ivoire" },
  { id: 'euro-fresh', name_fr: 'EuroFresh BV', name_en: 'EuroFresh BV', description_fr: 'Fournisseur européen de légumes frais et de pommes de terre calibrées, certifié GlobalGAP.', description_en: 'European supplier of fresh vegetables and calibrated potatoes, GlobalGAP certified.', logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200&q=80', country: 'Pays-Bas' },
]

// ── MIGRATION ───────────────────────────────────────────────────
async function migrate() {
  console.log('Début de la migration...\n')

  const { error: e1 } = await supabase.from('products').upsert(products)
  if (e1) console.error('❌ products:', e1.message)
  else console.log(`✅ ${products.length} produits insérés`)

  const { error: e2 } = await supabase.from('news').upsert(news)
  if (e2) console.error('❌ news:', e2.message)
  else console.log(`✅ ${news.length} articles insérés`)

  const { error: e3 } = await supabase.from('partners').upsert(partners)
  if (e3) console.error('❌ partners:', e3.message)
  else console.log(`✅ ${partners.length} partenaires insérés`)

  console.log('\nMigration terminée.')
}

migrate()
